# Generated by Django 6.1.1 on 2026-10-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0005_employee_department_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history', to='users.employee'),
        ),
    ]
