# Generated by Django 6.1.1 on 2026-09-30 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], default='New', max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired'), ('Lost', 'Lost')], default='Available', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
        ),
    ]
